# Generated by Django 3.0 on 2019-12-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalperson',
            name='person',
        ),
        migrations.AddField(
            model_name='legalperson',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person'),
            preserve_default=False,
        ),
    ]
