# Generated by Django 3.0 on 2019-12-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191211_2146'),
    ]

    operations = [
        migrations.RenameField(
            old_name='person_ptr',
            new_name='person',
            model_name='legalperson'
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Person'),
        )
    ]
