# Generated by Django 3.0 on 2020-01-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200107_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
