# Generated by Django 3.0 on 2020-01-09 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200107_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='legalperson',
            options={'verbose_name': 'Legal person', 'verbose_name_plural': 'Legal people'},
        ),
        migrations.AlterModelOptions(
            name='naturalperson',
            options={'verbose_name': 'Natural person', 'verbose_name_plural': 'Natural people'},
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='municipal_registration',
            field=models.CharField(max_length=18, verbose_name='Municipal registration'),
        ),
        migrations.AlterField(
            model_name='legalperson',
            name='state_registration',
            field=models.CharField(max_length=18, verbose_name='State registration'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='nationality',
            field=models.CharField(max_length=40, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='naturalness',
            field=models.CharField(max_length=30, verbose_name='Naturalness'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='person',
            name='document',
            field=models.CharField(max_length=16, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(max_length=30, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('number', models.CharField(max_length=5, verbose_name='Number')),
                ('complement', models.CharField(blank=True, max_length=50, verbose_name='Complement')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Person')),
                ('tags', models.ManyToManyField(blank=True, related_name='addresses', related_query_name='address', to='core.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
